### ISSUE TITLE
更新后私聊登录功能失效，私聊bot无反应

### ISSUE THREAD

**Issue by CYDXDianXian** [eggggi/yobot_remix#10]
3天前的旧版本私聊登录功能正常，但是更新到最新版后私聊登录功能失效，检查了cqgo的允许发送临时会话也已经开启，对比了历史commits没看懂哪里出了问题，作者大大帮忙看下感谢！

**Comment by CYDXDianXian** [comment]
已经看到了作者大大的修复更新commits a077391e142bd9070df7bf4483a122062c388107 实测更新完问题解决，感谢作者大大！

**Comment by eggggi** [comment]
\_(:з)∠)_
