### ISSUE TITLE
更新最新版本后，后台报刀失败了

### ISSUE THREAD

**Issue by zhtyirg3** [eggggi/yobot_remix#102]
![1e5f48eefb038c8c48cc0ff29e3daf21](https://github.com/eggggi/yobot_remix/assets/55908974/4595895e-3a36-445b-994a-81e27c9065a6)
大佬，我覆盖更新之后，发现后台进去报刀失败了，群里报刀可以，这是什么情况？

**Comment by eggggi** [comment]
ctrl+f5刷新页面

**Comment by zhtyirg3** [comment]
> ctrl+f5刷新页面

可以了，还有一个小问题，在后台报刀之后，群消息回复会带乱码，这个是哪里有问题了吗
![23ab0601ed7da663c8170de69bd80248](https://github.com/eggggi/yobot_remix/assets/55908974/b589bede-3329-49ad-97a3-d95845051de1)

**Comment by eggggi** [comment]
这个不是乱码，只是没获取到qq号。没啥影响建议先无视 \_(:з)∠)_

**Comment by zhtyirg3** [comment]
> 这个不是乱码，只是没获取到qq号。没啥影响建议先无视 _(:з)∠)_

确实，就是强迫症，感觉老是有英文，😄，谢谢大佬

**Comment by cca2878** [comment]
> > 这个不是乱码，只是没获取到qq号。没啥影响建议先无视 _(:з)∠)_
> 
> 确实，就是强迫症，感觉老是有英文，😄，谢谢大佬

实在看着不舒服可以到gocqhttp设置里面把无效cq码原样发送改成忽略。
（不利于debug，所以一般不关）
