### ISSUE TITLE
Yobot有可能与qq频道实现对接吗

### ISSUE THREAD

**Issue by RyanJiang184** [eggggi/yobot_remix#104]
频繁的风控使得qq机器人会战报刀异常的不稳定，就yobot来说，未来有可能实现在qq频道使用吗

**Comment by eggggi** [comment]
只能说有考虑过，但实际做起来还是有点麻烦，但过段时间有空了再研究 \_(:з)∠)_

**Comment by wulu318** [comment]
同求，只有公会战功能是刚需，如果能在官方频道接口使用会方便很多

**Comment by liyk123** [comment]
可以参考一下这个https://github.com/Hoshinonyaruko/Gensokyo

**Comment by V1046-R** [comment]
试过把yobot接到QQ频道中，但是发不出消息…
同等e佬一个QQ频道的升级（

**Comment by liyk123** [comment]
> 试过把yobot接到QQ频道中，但是发不出消息… 同等e佬一个QQ频道的升级（

大佬可能最近太忙了😂，都没有Git上的活动了，gensokyo这边也将进行适配。

**Comment by V1046-R** [comment]
> > 试过把yobot接到QQ频道中，但是发不出消息… 同等e佬一个QQ频道的升级（
> 
> 大佬可能最近太忙了😂，都没有Git上的活动了，gensokyo这边也将进行适配。

那就等等gensokyo好了TAT

**Comment by liyk123** [comment]
> > > 试过把yobot接到QQ频道中，但是发不出消息… 同等e佬一个QQ频道的升级（
> > 
> > 
> > 大佬可能最近太忙了😂，都没有Git上的活动了，gensokyo这边也将进行适配。
> 
> 那就等等gensokyo好了TAT

https://github.com/Hoshinonyaruko/Gensokyo/issues/97
yobot的用的handle_quick_operation_async是自定义行为，所以暂且没办法支持，如果有熟悉golang的大佬，可以去gensokyo帮忙适配一下，或者把本项目的消息响应标准化

**Comment by liyk123** [comment]
> > > > 试过把yobot接到QQ频道中，但是发不出消息… 同等e佬一个QQ频道的升级（
> > > 
> > > 
> > > 大佬可能最近太忙了😂，都没有Git上的活动了，gensokyo这边也将进行适配。
> > 
> > 
> > 那就等等gensokyo好了TAT
> 
> [Hoshinonyaruko/Gensokyo#97](https://github.com/Hoshinonyaruko/Gensokyo/issues/97) yobot的用的handle_quick_operation_async是自定义行为，所以暂且没办法支持，如果有熟悉golang的大佬，可以去gensokyo帮忙适配一下，或者把本项目的消息响应标准化

好消息，gensokyo已经适配完成！

**Comment by Qielanyinyin** [comment]
> > > > > 试过把yobot接到QQ频道中，但是发不出消息… 同等e佬一个QQ频道的升级（
> > > > 
> > > > 
> > > > 大佬可能最近太忙了😂，都没有Git上的活动了，gensokyo这边也将进行适配。
> > > 
> > > 
> > > 那就等等gensokyo好了TAT
> > 
> > 
> > [Hoshinonyaruko/Gensokyo#97](https://github.com/Hoshinonyaruko/Gensokyo/issues/97) yobot的用的handle_quick_operation_async是自定义行为，所以暂且没办法支持，如果有熟悉golang的大佬，可以去gensokyo帮忙适配一下，或者把本项目的消息响应标准化
> 
> 好消息，gensokyo已经适配完成！

试了下，可以。就是发不了连接登陆网页不方便。接下来就是如何过审了，不然20人的沙盒不够用。

**Comment by liyk123** [comment]
> > > > > > 试过把yobot接到QQ频道中，但是发不出消息… 同等e佬一个QQ频道的升级（
> > > > > 
> > > > > 
> > > > > 大佬可能最近太忙了😂，都没有Git上的活动了，gensokyo这边也将进行适配。
> > > > 
> > > > 
> > > > 那就等等gensokyo好了TAT
> > > 
> > > 
> > > [Hoshinonyaruko/Gensokyo#97](https://github.com/Hoshinonyaruko/Gensokyo/issues/97) yobot的用的handle_quick_operation_async是自定义行为，所以暂且没办法支持，如果有熟悉golang的大佬，可以去gensokyo帮忙适配一下，或者把本项目的消息响应标准化
> > 
> > 
> > 好消息，gensokyo已经适配完成！
> 
> 试了下，可以。就是发不了连接登陆网页不方便。接下来就是如何过审了，不然20人的沙盒不够用。

发链接需要已经备案的域名服务器，过审需要填写自测模板

**Comment by V1046-R** [comment]
> > > > > 试过把yobot接到QQ频道中，但是发不出消息… 同等e佬一个QQ频道的升级（
> > > > 
> > > > 
> > > > 大佬可能最近太忙了😂，都没有Git上的活动了，gensokyo这边也将进行适配。
> > > 
> > > 
> > > 那就等等gensokyo好了TAT
> > 
> > 
> > [Hoshinonyaruko/Gensokyo#97](https://github.com/Hoshinonyaruko/Gensokyo/issues/97) yobot的用的handle_quick_operation_async是自定义行为，所以暂且没办法支持，如果有熟悉golang的大佬，可以去gensokyo帮忙适配一下，或者把本项目的消息响应标准化
> 
> 好消息，gensokyo已经适配完成！

测试完毕，基本算是完美适配，至于面板的链接问题那都是小事情了！
喜大普奔！感谢
