### ISSUE TITLE
更新后跨阶段boss血量问题依旧没能解决

### ISSUE THREAD

**Issue by CYDXDianXian** [eggggi/yobot_remix#11]
现存问题依旧与 #8 的反馈一致，测试多遍。
麻烦老师再看下了，感谢~

**Comment by eggggi** [comment]
好了
![ELY {_I9$FTWN5_AV GCO_P](https://user-images.githubusercontent.com/49231933/176501057-fbf75446-793f-48c8-8cb3-b62184829cc4.png)

**Comment by CYDXDianXian** [comment]
哇！测试了一下，这下真的好了！感谢老师凌晨还在修bug！那么，老师好好睡吧！不打扰你啦！晚安！！
