### ISSUE TITLE
私聊问题

### ISSUE THREAD

**Issue by sagiriyo** [eggggi/yobot_remix#112]
为什么群聊里面指令和图片都能推送出来
私聊的就无法推送
发登录没有链接
用的
![536535734a9a971f67554b13ef7f3b17](https://github.com/eggggi/yobot_remix/assets/76777320/cd30c87b-f40b-4beb-91d8-1ae163c89adc)
![b7fa2bc945834332bd0499ba8d071937](https://github.com/eggggi/yobot_remix/assets/76777320/7a4447e3-94ae-4acd-b1ac-a2ff72105ed6)

**Comment by sagiriyo** [comment]
qqnt的liteloader框架和Lagrange.OneBot都试过了 就是不推送私聊的链接

**Comment by sagiriyo** [comment]
已解决

**Comment by eggggi** [comment]
https://github.com/eggggi/yobot_remix/commit/750a06867af677be44d0b090428d1fd9f2d092c0
