### ISSUE TITLE
插件版使用的问题

### ISSUE THREAD

**Issue by Momona0v0** [eggggi/yobot_remix#113]
代码小白求救
由于gocq停止服务且风控严重，无法使用，自己改用了LiteLoaderQQNT的LLonebot。出现了一些问题
①将hoshino（8080端口）和yobot（9222端口）分开使用时，hoshino正常运行，yobot仅能接受消息，无法发送（可能是LLonebot的缺陷）
②将yobot作为hoshino插件使用，仅打开hoshino时，无法启动yobot的网页端服务
③将yobot作为hoshino插件使用，且同时打开hoshino的run.py和yobot的main.py，qq仅监听8080端口时，网页版的“面板”处数据不能与qq群内的进度图片同步，但是报刀和查刀界面正常
④将yobot作为hoshino插件使用，且同时打开hoshino和yobot，qq同时监听8080和9222端口时，报刀消息会同时被8080和9222端口接受并加载到网页端，导致报1刀变2刀的情况

个人推测可能是yobot作为插件版使用时，qq群发送“状态”时候发出的进度图片仅使用8080传输来的数据，网页端“面板”界面仅使用9222端口传输来的数据，“报刀”界面处同时接受8080和9222的数据，收发qq群消息只能通过8080
能否有办法处理这个问题？比如
①适配LiteLoaderQQNT（应该比较麻烦吧）
②将yobot的网页服务单独拉出来，使其可以被hoshino启动
③④使网页端的“报刀”界面仅接受8080或9222的数据
或者让群聊端的图片基于网页端的数据生成等

**Comment by Momona0v0** [comment]
将yobot复制两份，一份作为插件版一份独立使用，并只打开独立使用的yobot的main.py以后避开了上述问题。
群聊消息通过hoshino的8080端口收发，由于没有启动插件版的yobot，8080端口收到的报刀消息无法加载到yobot网页版，仅能加载到群聊版的图片上。而通过独立的yobot仅接受来自9222端口的报刀消息，并加载到网页端。
没有根本性解决上述问题，而且这样会导致网页端（接受9222端口信息）和群聊端（接受8080端口的信息）的boss状态不同步。一旦修改boss状态，无法同步到群聊端去。

**Comment by othinus001** [comment]
> 代码小白求救 由于gocq停止服务且风控严重，无法使用，自己改用了LiteLoaderQQNT的LLonebot。出现了一些问题 ①将hoshino（8080端口）和yobot（9222端口）分开使用时，hoshino正常运行，yobot仅能接受消息，无法发送（可能是LLonebot的缺陷） ②将yobot作为hoshino插件使用，仅打开hoshino时，无法启动yobot的网页端服务 ③将yobot作为hoshino插件使用，且同时打开hoshino的run.py和yobot的main.py，qq仅监听8080端口时，网页版的“面板”处数据不能与qq群内的进度图片同步，但是报刀和查刀界面正常 ④将yobot作为hoshino插件使用，且同时打开hoshino和yobot，qq同时监听8080和9222端口时，报刀消息会同时被8080和9222端口接受并加载到网页端，导致报1刀变2刀的情况
> 
> 个人推测可能是yobot作为插件版使用时，qq群发送“状态”时候发出的进度图片仅使用8080传输来的数据，网页端“面板”界面仅使用9222端口传输来的数据，“报刀”界面处同时接受8080和9222的数据，收发qq群消息只能通过8080 能否有办法处理这个问题？比如 ①适配LiteLoaderQQNT（应该比较麻烦吧） ②将yobot的网页服务单独拉出来，使其可以被hoshino启动 ③④使网页端的“报刀”界面仅接受8080或9222的数据 或者让群聊端的图片基于网页端的数据生成等

为什么两个端口不填一样的？

**Comment by Momona0v0** [comment]
> > 代码小白求救 由于gocq停止服务且风控严重，无法使用，自己改用了LiteLoaderQQNT的LLonebot。出现了一些问题 ①将hoshino（8080端口）和yobot（9222端口）分开使用时，hoshino正常运行，yobot仅能接受消息，无法发送（可能是LLonebot的缺陷） ②将yobot作为hoshino插件使用，仅打开hoshino时，无法启动yobot的网页端服务 ③将yobot作为hoshino插件使用，且同时打开hoshino的run.py和yobot的main.py，qq仅监听8080端口时，网页版的“面板”处数据不能与qq群内的进度图片同步，但是报刀和查刀界面正常 ④将yobot作为hoshino插件使用，且同时打开hoshino和yobot，qq同时监听8080和9222端口时，报刀消息会同时被8080和9222端口接受并加载到网页端，导致报1刀变2刀的情况
> > 个人推测可能是yobot作为插件版使用时，qq群发送“状态”时候发出的进度图片仅使用8080传输来的数据，网页端“面板”界面仅使用9222端口传输来的数据，“报刀”界面处同时接受8080和9222的数据，收发qq群消息只能通过8080 能否有办法处理这个问题？比如 ①适配LiteLoaderQQNT（应该比较麻烦吧） ②将yobot的网页服务单独拉出来，使其可以被hoshino启动 ③④使网页端的“报刀”界面仅接受8080或9222的数据 或者让群聊端的图片基于网页端的数据生成等
> 
> 为什么两个端口不填一样的？

如果填了一样的，就只能打开其中一个了，另一个会因为端口被占用导致无法使用
如果只开hoshino不开yobot，网页服务无法使用，只开yobot不开hoshino会发不出群聊消息

**Comment by othinus001** [comment]
> > > 代码小白求救 由于gocq停止服务且风控严重，无法使用，自己改用了LiteLoaderQQNT的LLonebot。出现了一些问题 ①将hoshino（8080端口）和yobot（9222端口）分开使用时，hoshino正常运行，yobot仅能接受消息，无法发送（可能是LLonebot的缺陷） ②将yobot作为hoshino插件使用，仅打开hoshino时，无法启动yobot的网页端服务 ③将yobot作为hoshino插件使用，且同时打开hoshino的run.py和yobot的main.py，qq仅监听8080端口时，网页版的“面板”处数据不能与qq群内的进度图片同步，但是报刀和查刀界面正常 ④将yobot作为hoshino插件使用，且同时打开hoshino和yobot，qq同时监听8080和9222端口时，报刀消息会同时被8080和9222端口接受并加载到网页端，导致报1刀变2刀的情况
> > > 个人推测可能是yobot作为插件版使用时，qq群发送“状态”时候发出的进度图片仅使用8080传输来的数据，网页端“面板”界面仅使用9222端口传输来的数据，“报刀”界面处同时接受8080和9222的数据，收发qq群消息只能通过8080 能否有办法处理这个问题？比如 ①适配LiteLoaderQQNT（应该比较麻烦吧） ②将yobot的网页服务单独拉出来，使其可以被hoshino启动 ③④使网页端的“报刀”界面仅接受8080或9222的数据 或者让群聊端的图片基于网页端的数据生成等
> > 
> > 
> > 为什么两个端口不填一样的？
> 
> 如果填了一样的，就只能打开其中一个了，另一个会因为端口被占用导致无法使用 如果只开hoshino不开yobot，网页服务无法使用，只开yobot不开hoshino会发不出群聊消息

我一样的端口用了好几年了，
请先更新yobot，转移yobot_data文件夹，更新依赖
然后请从②入手，我推测原因是你有插件也涉及网页端占用，如autopcr/原神等巴拉巴拉乱七八糟的。可以在打开每个插件代码搜下是否含有flask，可是试着全关了只开yobot插件测试。
插件版还开mian.py有点异想天开了

**Comment by Momona0v0** [comment]
> > > > 代码小白求救 由于gocq停止服务且风控严重，无法使用，自己改用了LiteLoaderQQNT的LLonebot。出现了一些问题 ①将hoshino（8080端口）和yobot（9222端口）分开使用时，hoshino正常运行，yobot仅能接受消息，无法发送（可能是LLonebot的缺陷） ②将yobot作为hoshino插件使用，仅打开hoshino时，无法启动yobot的网页端服务 ③将yobot作为hoshino插件使用，且同时打开hoshino的run.py和yobot的main.py，qq仅监听8080端口时，网页版的“面板”处数据不能与qq群内的进度图片同步，但是报刀和查刀界面正常 ④将yobot作为hoshino插件使用，且同时打开hoshino和yobot，qq同时监听8080和9222端口时，报刀消息会同时被8080和9222端口接受并加载到网页端，导致报1刀变2刀的情况
> > > > 个人推测可能是yobot作为插件版使用时，qq群发送“状态”时候发出的进度图片仅使用8080传输来的数据，网页端“面板”界面仅使用9222端口传输来的数据，“报刀”界面处同时接受8080和9222的数据，收发qq群消息只能通过8080 能否有办法处理这个问题？比如 ①适配LiteLoaderQQNT（应该比较麻烦吧） ②将yobot的网页服务单独拉出来，使其可以被hoshino启动 ③④使网页端的“报刀”界面仅接受8080或9222的数据 或者让群聊端的图片基于网页端的数据生成等
> > > 
> > > 
> > > 为什么两个端口不填一样的？
> > 
> > 
> > 如果填了一样的，就只能打开其中一个了，另一个会因为端口被占用导致无法使用 如果只开hoshino不开yobot，网页服务无法使用，只开yobot不开hoshino会发不出群聊消息
> 
> 我一样的端口用了好几年了， 请先更新yobot，转移yobot_data文件夹，更新依赖 然后请从②入手，我推测原因是你有插件也涉及网页端占用，如autopcr/原神等巴拉巴拉乱七八糟的。可以在打开每个插件代码搜下是否含有flask，可是试着全关了只开yobot插件测试。 插件版还开mian.py有点异想天开了

好的，等公会战结束后我尝试一下，谢谢

**Comment by BlackBox999** [comment]
> 代码小白求救 由于gocq停止服务且风控严重，无法使用，自己改用了LiteLoaderQQNT的LLonebot。出现了一些问题 ①将hoshino（8080端口）和yobot（9222端口）分开使用时，hoshino正常运行，yobot仅能接受消息，无法发送（可能是LLonebot的缺陷） ②将yobot作为hoshino插件使用，仅打开hoshino时，无法启动yobot的网页端服务 ③将yobot作为hoshino插件使用，且同时打开hoshino的run.py和yobot的main.py，qq仅监听8080端口时，网页版的“面板”处数据不能与qq群内的进度图片同步，但是报刀和查刀界面正常 ④将yobot作为hoshino插件使用，且同时打开hoshino和yobot，qq同时监听8080和9222端口时，报刀消息会同时被8080和9222端口接受并加载到网页端，导致报1刀变2刀的情况
> 
> 个人推测可能是yobot作为插件版使用时，qq群发送“状态”时候发出的进度图片仅使用8080传输来的数据，网页端“面板”界面仅使用9222端口传输来的数据，“报刀”界面处同时接受8080和9222的数据，收发qq群消息只能通过8080 能否有办法处理这个问题？比如 ①适配LiteLoaderQQNT（应该比较麻烦吧） ②将yobot的网页服务单独拉出来，使其可以被hoshino启动 ③④使网页端的“报刀”界面仅接受8080或9222的数据 或者让群聊端的图片基于网页端的数据生成等

不，我用普通版YOBOT运行，LLoneBOT的CQ上报也是只能接不能发，我现在换NapCat了，CQ上报目前正常

**Comment by eggggi** [comment]
用[拉格朗日](https://github.com/LagrangeDev/Lagrange.Core)试试，我现在用的这个，私聊问题我上午提交了一个改动

**Comment by Momona0v0** [comment]
LLOnebot 的[新版本](https://github.com/LLOneBot/LLOneBot/issues/186)已经解决了发不出消息的问题，今后可以用普通版运行了
该问题已经解决
