### ISSUE TITLE
数据分析界面的cdn寄了。

### ISSUE THREAD

**Issue by tusky94** [eggggi/yobot_remix#115]
https://cdn.bootcdn.net/ajax/libs/echarts/4.7.0/echarts.min.js
![image](https://github.com/user-attachments/assets/103fd7dd-b296-4d3f-899f-abcd3d1984b7)

**Comment by duoshoumiao** [comment]
<script src="https://cdn.bootcdn.net/ajax/libs/echarts/4.7.0/echarts.min.js"></script>
改成
<script src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>
