### ISSUE TITLE
冒号留言相关功能无效

### ISSUE THREAD

**Issue by cadaeibf1** [eggggi/yobot_remix#13]
原版yobot可以使用类似“预约1：5点来”这样实现预约表中的留言。印象里中英文冒号都可以实现。
可当前版本使用冒号无效，不管是在预约场合还是在挂树场合。
如图：
![QQ截图20220705001521](https://user-images.githubusercontent.com/65361365/177190963-521b2209-d425-4cc0-be70-4b1b426d7ea5.png)
![QQ截图20220705000836](https://user-images.githubusercontent.com/65361365/177190663-07dbf233-ebf3-450e-b7f4-99693ca0d44e.png)
![QQ截图20220705000915](https://user-images.githubusercontent.com/65361365/177190678-c9aa54e3-986b-4ab3-87e8-3d6f7ff22633.png)
![QQ截图20220705000935](https://user-images.githubusercontent.com/65361365/177190701-c04c3f40-2bd1-4ff1-a013-7c170ecbd847.png)

另外还有个问题是。由于当前国服尚未更新自由出刀模式，是不是意味着我无法在remix版中实现，尾刀1王，提示2王预约者这个功能？

感谢老师

**Comment by eggggi** [comment]
冒号留言这个我还没完善，过两天我整一下。\_(:з)∠)_

因为这个remix版是按新版会战的逻辑做的，不建议用在还没更新新版会战的国服。
新版会战的预约是等下一个已预约的boss刷新就会@提醒。由于5个王可以随意挑战，尾刀1王的时候是完全没必要提醒2王预约者的，除非是在只剩1王的情况下，其它boss全部0血，这时5个王会同时刷新并同时提醒5个王的预约者。
当然，如果你能看懂我写的代码，倒是可以尝试改一下，不过我并不建议，因为我写的逻辑很脆弱（我好菜），说不定会牵一发而动全身\_(:з)∠)_
（boss_num，qqid，group_id这几个字段一直在string和int之间反复横跳）

**Comment by cadaeibf1** [comment]
谢谢老师！那既然目前国服环境对不上remix的逻辑，那留言问题其实也就不着急了~
