### ISSUE TITLE
CDN全挂了，可否移除 cdn，全部改用本地静态资源？

### ISSUE THREAD

**Issue by CYDXDianXian** [eggggi/yobot_remix#14]
![image](https://user-images.githubusercontent.com/71607036/180452676-72958cf0-0a38-4ba9-b461-36db17835afe.png)

曾自行尝试移除cdn并换用本地资源，但是试了一天总发现有无法解决的问题，主要是vue上的报错。。本人并不会vue，所以还是来求助老师来了，麻烦老师了！感谢！

**Comment by CYDXDianXian** [comment]
[YoCool](https://github.com/A-kirami/YoCool) 看到yocool已经更新了本地资源

**Comment by eggggi** [comment]
可以的，前段时间雨滴佬已经把cdn资源全部改成本地了，可以去看看[yobot](https://github.com/yuudi/yobot)的更新

**Comment by CYDXDianXian** [comment]
好了，问题都解决了，已提交pr

**Comment by eggggi** [comment]
近期没啥时间看这个，先无脑替换cdn到我自己的个人服务器上了，晚点再研究改成本地资源0.0

**Comment by CYDXDianXian** [comment]
本地资源我已经改好了，PR已提交，群友也帮忙测试了没啥问题了

**Comment by CYDXDianXian** [comment]
啊这。。。你这边换完CDN置换PR又冲突了。。。你那边看着revert commit然后合并一下就好了，都改好了没必要再改一遍惹

**Comment by eggggi** [comment]
等晚点我有时间了过一遍你提交的pr，没问题我再点合并(っ °Д °;)っ

**Comment by CYDXDianXian** [comment]
OK，麻烦绘月老师了

**Comment by CYDXDianXian** [comment]
PR的分支冲突已解决~
