### ISSUE TITLE
重启功能和更新功能无法使用

### ISSUE THREAD

**Issue by JiangShi-GitHub** [eggggi/yobot_remix#18]
输入重启之后没反应，然后设置项里面调整boss血量调整失败

**Comment by eggggi** [comment]
重启功能我也没用过，如果有报错信息什么的截图发一下就好了。
修改状态是否点了右下角修改？取消或者x掉是修改不了的

**Comment by JiangShi-GitHub** [comment]
就是给bot发送“重启”之后bot端也没反应，然后服务器端也没反应，但是当时看YoBot原文档应该是有这个功能的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月26日 02:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [eggggi/yobot_remix] 重启功能和更新功能无法使用 (Issue #18) |

重启功能我也没用过，如果有报错信息什么的截图发一下就好了。
修改状态是否点了右下角修改？取消或者x掉是修改不了的

**Comment by eggggi** [comment]
oh，重启已经被我删了0.0
