### ISSUE TITLE
增加阶段数后，当报刀的数据达到所增加的阶段数时报错

### ISSUE THREAD

**Issue by KnightK22** [eggggi/yobot_remix#20]
大佬好
如图
![屏幕截图 2023-01-28 012843](https://user-images.githubusercontent.com/57353187/215154746-82b3bf3b-9c3c-4e11-86e5-8a9f7652cc7b.png)
报错‘server error, info:list index out of range’，请问这个要如何解决呢

**Comment by eggggi** [comment]
啊。。经典越界。。。截图栞栞后端的具体报错信息

**Comment by KnightK22** [comment]
![屏幕截图 2023-01-28 125512](https://user-images.githubusercontent.com/57353187/215242834-ceabcaf7-4afc-470b-9355-e78173e58aec.png)

所选的api/就是出现报错时出来的

**Comment by eggggi** [comment]
啊这。。我是指yobot或hoshino的日志报错信息

**Comment by KnightK22** [comment]
![屏幕截图 2023-01-28 135229](https://user-images.githubusercontent.com/57353187/215248723-aba48259-9245-4986-a751-dfe932527c1f.png)
大佬是这个吧

**Comment by eggggi** [comment]
懂了，等我出完刀就修

**Comment by KnightK22** [comment]
大佬幸苦了

**Comment by eggggi** [comment]
找到问题了。改血量数据必须要重启。报错的原因是未重启的时候，周目对应的阶段改了，但boss血量数据没改，导致的越界错误。修改提交了

**Comment by KnightK22** [comment]
> 找到问题了。改血量数据必须要重启。报错的原因是未重启的时候，周目对应的阶段改了，但boss血量数据没改，导致的越界错误。修改提交了

谢谢大佬，大佬牛逼
