### ISSUE TITLE
网页端点击进入公会战面板报错：missing key：‘6’

### ISSUE THREAD

**Issue by KnightK22** [eggggi/yobot_remix#23]
大佬打扰了，按照上一个issue（https://github.com/eggggi/yobot_remix/issues/20）改了之后，现在网页端点击进入公会战面板就会报错
![屏幕截图 2023-02-02 210443](https://user-images.githubusercontent.com/57353187/216333409-875b6843-c56e-40c0-a89c-f01cdb832bd1.png)
这个是报错后后端的信息
![屏幕截图 2023-02-02 210524](https://user-images.githubusercontent.com/57353187/216333577-cabf5bb5-ec48-45bc-ac51-72b2f179c303.png)
这个是关闭进程时的报错信息
![屏幕截图 2023-02-02 210610](https://user-images.githubusercontent.com/57353187/216333686-75d615fa-d076-4bab-91a4-1eb6f521a191.png)

**Comment by eggggi** [comment]
或许是旧数据影响到了吧，进设置删除这个档案再看看

**Comment by KnightK22** [comment]
> 或许是旧数据影响到了吧，进设置删除这个档案再看看

试过了大佬，把公会删了新建还是报这个错

**Comment by eggggi** [comment]
yobot后端报错截全一点

**Comment by eggggi** [comment]
看这个提示应该是json取数据出错，但没有具体出错位置没办法判断是什么原因导致的。我自己跑没发现这个问题，应该是个隐藏bug，麻烦发下报错时yobot的后端报错信息，就是你第二张图的上面部分

**Comment by KnightK22** [comment]
> 看这个提示应该是json取数据出错，但没有具体出错位置没办法判断是什么原因导致的。我自己跑没发现这个问题，应该是个隐藏bug，麻烦发下报错时yobot的后端报错信息，就是你第二张图的上面部分

![屏幕截图 2023-02-03 004414](https://user-images.githubusercontent.com/57353187/216387500-3d033c41-94e2-4c45-b3d9-d877d541f549.png)
这就是上面所有的信息了

**Comment by eggggi** [comment]
这个打印出来的6是在哪个位置，是你自己加的吗？只有这些信息实在没办法判断是哪里出了问题，可以说一下第一次出现这种情况之前做了什么操作吗

**Comment by KnightK22** [comment]
> 这个打印出来的6是在哪个位置，是你自己加的吗？只有这些信息实在没办法判断是哪里出了问题，可以说一下第一次出现这种情况之前做了什么操作吗

解决了 大佬，重新git pull就没有问题了，大佬幸苦
