### ISSUE TITLE
周目刷新后可挑战Boss的提醒不能自动取消

### ISSUE THREAD

**Issue by OREOCODEDEV** [eggggi/yobot_remix#25]
[realize.py 624行](https://github.com/eggggi/yobot_remix/blob/stable/src/client/ybplugins/clan_battle/components/realize.py#L624)中，因周目数刷新提醒预约后取消预约所操作的`Clan_group`实例并非`challenge`方法中的`group`，所以`challenge`内的`group`保存时会覆盖掉`subscribe_remind`方法内取消预约的结果，导致周目刷新的提醒不能自动取消

```Python
group:Clan_group = Clan_group.get_or_none(group_id=group_id) #541行
...
if _health == 0: subscribe_remind(self, group_id, _boss_num)# 如果挪过来的血量为0，则发送预约提醒 #624行
...
group.save() #632行
```

复现方法：

1. 切换到新的档案以便于测试
2. 击败2次3号Boss，使3号Boss进入不可挑战状态
3. 预约3号Boss
4. 分别击败1次1、2、4、5号Boss
5. 这时会因为3号Boss刷新，yobot发送预约提醒
6. 查询预约表，3号Boss发送过的提醒仍在预约表内

**Comment by OREOCODEDEV** [comment]
通过给`subscribe_remind`和`subscribe_cancel`传入`Clan_group`实例修复了这个问题，但是代码风格就跟项目不太一致了，不知道有没有合适一点的解决方法
https://github.com/OREOCODEDEV/yobot_remix/commit/23bebb6c7fb9d4eea513a04d5e8d9fb84b316c16

**Comment by eggggi** [comment]
想到了一个方法，确保每次获取Clan_group实例是同一个就行了，但貌似会占用更多的内存，不过应该影响不大，摸了_(:з)∠)_ https://github.com/eggggi/yobot_remix/commit/a129b1db069335ced24afd4fa790323d24be31ce

**Comment by OREOCODEDEV** [comment]
![O2ZSH~OD`JBZPRWSID`{CAM](https://user-images.githubusercontent.com/44545625/216905304-bad044d2-87f2-4066-8117-6cf40d6fd1f9.gif)

未曾设想过的道路
