### ISSUE TITLE
网页端页面不显示

### ISSUE THREAD

**Issue by pach128** [eggggi/yobot_remix#29]
dalao您好，打扰下，我是以插件版用的，将您的项目git clone到modules下，然后将原来yobot的yobot_data目录拷到您的项目里，最后启动服务，目前qq群里返回都是正常的，但页面版不显示
![image](https://user-images.githubusercontent.com/65009140/218319388-9fcbe89f-15ca-4187-beeb-ad86dc046dee.png)
我通过F12，发现错误的页面返回是404，这是什么情况？麻烦dalao指导下，非常感谢
![image](https://user-images.githubusercontent.com/65009140/218319441-2adb827a-70ae-4144-98b6-9c53186b1788.png)

**Comment by eggggi** [comment]
按ctrl+f5刷新一下试试

**Comment by pach128** [comment]
额，好了，多谢dalao指导，原来是这个问题，我翻了半天日志没有报错，尴尬
