### ISSUE TITLE
运行报错There is no current event loop in thread

### ISSUE THREAD

**Issue by XiaoFuOS** [eggggi/yobot_remix#3]
我实在找不到解决方法了哈哈哈
![QQ图片20220526111525](https://user-images.githubusercontent.com/103229747/170408771-d76e0327-c9f7-4f69-ba4f-b9e87ac58fc8.png)

**Comment by eggggi** [comment]
你的py版本是3.10？我不太清楚用这个版本会发生什么，我的是3.8。。如果你之前能正常使用原版的yobot的话，理论上来说也是能正常用这个魔改版的 0.0

**Comment by XiaoFuOS** [comment]
> 你的py版本是3.10？我不太清楚用这个版本会发生什么，我的是3.8。。如果你之前能正常使用原版的yobot的话，理论上来说也是能正常用这个魔改版的 0.0

之前用的便捷版，没有当作插件来使用，我换下python3.8.8试下吧，不行再看看

**Comment by eggggi** [comment]
查了一下，貌似是自动识别时区出现问题，你是不是挂了梯子

**Comment by XiaoFuOS** [comment]
> 查了一下，貌似是自动识别时区出现问题，你是不是挂了梯子

没挂，华为云服务器

**Comment by eggggi** [comment]
没见过的情况0.0。。还是先检查下py版本和aiocqhttp版本吧

**Comment by XiaoFuOS** [comment]
> 没见过的情况0.0。。还是先检查下py版本和aiocqhttp版本吧

换了Python版本了，确实没那个报错了。但是地址好像报错了，就很怪
![QQ截图20220526145625](https://user-images.githubusercontent.com/103229747/170434849-b06fe817-db53-45db-8da9-25df8a1c97b6.png)

**Comment by eggggi** [comment]
> > 没见过的情况0.0。。还是先检查下py版本和aiocqhttp版本吧
> 
> 换了Python版本了，确实没那个报错了。但是地址好像报错了，就很怪 ![QQ截图20220526145625](https://user-images.githubusercontent.com/103229747/170434849-b06fe817-db53-45db-8da9-25df8a1c97b6.png)

yobot_config.json里面的内容填好了吗

**Comment by XiaoFuOS** [comment]
> > > 没见过的情况0.0。。还是先检查下py版本和aiocqhttp版本吧
> > 
> > 
> > 换了Python版本了，确实没那个报错了。但是地址好像报错了，就很怪 ![QQ截图20220526145625](https://user-images.githubusercontent.com/103229747/170434849-b06fe817-db53-45db-8da9-25df8a1c97b6.png)
> 
> yobot_config.json里面的内容填好了吗

除了host和port还有其他要填吗
![QQ截图20220526155513](https://user-images.githubusercontent.com/103229747/170444295-5e2e6954-033b-40ef-9570-0e534b2d6ef9.png)

**Comment by eggggi** [comment]
host填0.0.0.0

**Comment by XiaoFuOS** [comment]
> host填0.0.0.0

倒是正常
![1](https://user-images.githubusercontent.com/103229747/170452371-48a2a390-3f94-4e64-b139-ef000376b796.png)
运行了，但是似乎没反应，我现在运行的是cqhttp hoshin和本插件下client下的main.py

**Comment by eggggi** [comment]
插件版的话，是不需要再单独执行yobot的，直接在hoshino的__bot__.py加上yobot在modules里的文件夹名就好。记得在yobot_config.json填好access_token和client_salt

**Comment by XiaoFuOS** [comment]
> access_token

厚着脸皮想问，access_token和client_salt哪里获取QAQ

**Comment by eggggi** [comment]
client_salt可以无视，access_token对应__bot__.py里的ACCESS_TOKEN

**Comment by XiaoFuOS** [comment]
> client_salt可以无视，access_token对应__bot__.py里的ACCESS_TOKEN

[](https://github.com/Ice-Cirno/HoshinoBot/blob/master/hoshino/config_example/__bot__.py)
现在似乎没有那个选项了

**Comment by XiaoFuOS** [comment]
> 

https://github.com/Ice-Cirno/HoshinoBot/blob/master/hoshino/config_example/__bot__.py

**Comment by eggggi** [comment]
gocqhttp的config.yml里的access-token

**Comment by XiaoFuOS** [comment]
> gocqhttp的config.yml里的access-token
![QQ截图20220526180826](https://user-images.githubusercontent.com/103229747/170467140-e9f8bc35-a908-4cbe-bd3d-c664dab0b446.png)
加了重启过后，发指令也没反应

**Comment by XiaoFuOS** [comment]
> __bot__.py

__bot__.py上已经加了对应文件夹名字，就很怪，发创建任何指令都没反馈

**Comment by XiaoFuOS** [comment]
对了，作为hoshin的插件使用只需要吧client文件夹放module里吗，其他文件夹不要？

**Comment by eggggi** [comment]
不是，整个都要。你该不会是把__init__.py漏了 Σ(っ °Д °;)っ
![yobotpath](https://user-images.githubusercontent.com/49231933/170485014-c16f996a-579a-4192-beaf-ba0a9911a19c.png)

**Comment by XiaoFuOS** [comment]
没有，我全加的话没反应，只放clien却响应了，就很怪 Σ(っ °Д °;)っ

**Comment by XiaoFuOS** [comment]
![1](https://user-images.githubusercontent.com/103229747/170486291-669deecf-eea3-49dd-8c3c-b6f1ecd52782.png)
![2](https://user-images.githubusercontent.com/103229747/170486320-18d7c8be-e4c0-4885-9322-1af1e64b777d.png)
![3](https://user-images.githubusercontent.com/103229747/170486328-bc4d1a99-3fb9-4074-8a9c-73d179bf3920.png)
![4](https://user-images.githubusercontent.com/103229747/170486333-c2200ff5-624d-44a1-b14c-5bad0a39d0f6.png)
![5](https://user-images.githubusercontent.com/103229747/170486340-34e3179f-741a-4d96-9a31-16526b7cb484.png)
这配置有没有错嘛

**Comment by eggggi** [comment]
看起来没啥问题，要不你尝试下像我这个结构放？我也忘记了当时我为啥要套两层了。。

**Comment by XiaoFuOS** [comment]
> 看起来没啥问题，要不你尝试下像我这个结构放？我也忘记了当时我为啥要套两层了。。

多套了一层是可以了哈哈哈，但是~
![QQ截图20220526205850](https://user-images.githubusercontent.com/103229747/170492609-8cec3242-b562-44b3-8f7d-825bcf85202b.png)
面板，登录之类的网址进不去，对应9222端口也开了
![QQ截图20220526210302](https://user-images.githubusercontent.com/103229747/170493054-a6fda962-ef38-40ac-a639-46f0be63ccf7.png)

**Comment by eggggi** [comment]
有用宝塔面板吗，宝塔面板里面的端口也开一下

**Comment by XiaoFuOS** [comment]
> 有用宝塔面板吗，宝塔面板里面的端口也开一下

没用，纯win2012系统

**Comment by eggggi** [comment]
先试一下在win浏览器里输入localhost:9222看行不行，排除掉bot配置的问题。如果可以的话百度查下winserver的端口怎么开，我没用过winserver。。

**Comment by XiaoFuOS** [comment]
> localhost:9222
![QQ截图20220526220224](https://user-images.githubusercontent.com/103229747/170503390-5511a435-f412-4c8e-a838-e3edc72d6953.png)
服务器本地能正常打开，那应该是其他原因了

**Comment by XiaoFuOS** [comment]
![QQ截图20220526221447](https://user-images.githubusercontent.com/103229747/170505829-9fbed7ba-e149-4232-bf57-52adcd86ceaf.png)
莫不是只允许本地连接的原因

**Comment by XiaoFuOS** [comment]
> 

解决了，原因是127.0.0.1不允许外网访问，谢谢你
