### ISSUE TITLE
运行时会出现OS错误

### ISSUE THREAD

**Issue by CatSodaaa** [eggggi/yobot_remix#31]
![QQ图片20230311195723](https://user-images.githubusercontent.com/115628315/224483242-1dc979d2-6865-4087-85cd-b0651d91b189.png)
大佬麻烦看看怎么解决  其他的功能都是正常的 就状态和业绩表用不了。。。。

**Comment by OREOCODEDEV** [comment]
看着像是缺了字体文件，检查一下项目路径下的`.\src\client\ybplugins\clan_battle\components\fonts\msyh.ttf`文件是否存在，以及能不能被正常打开

**Comment by CatSodaaa** [comment]
> 

路径底下这个字体文件是存在的，是微软雅黑字体。安装字体前运行起来也报这个错，手动安装字体后跑起来报错也是这样。。。。不知道哪个环节出问题了。网上搜了一圈也是说可能是字体路径不正常，几个py文件打开看也没啥毛病。。搞不明白了，难受。

**Comment by eggggi** [comment]
检查一下ttf文件路径的权限，改成777试下

**Comment by OREOCODEDEV** [comment]
如果常用的方法不能解决这个问题，建议在`.src/client/ybplugins/clan_battle/components/realize.py`内34行上方插入下列代码以缩小排查范围：
```
print(FONTS)
print(os.path.isfile(FONTS))
```
插入并重启yobot后发送`状态`命令，在Exception抛出前应该会在控制台输出字体路径以及系统获取到的字体文件状态

**Comment by CatSodaaa** [comment]
> 检查一下ttf文件路径的权限，改成777试下

直接运行打包好的yobot.exe会出现os错误 我换了个方法 运行了主文件夹里的main.py文件 能跑起来 而且所有功能正常使用
太怪了。。。。。。

**Comment by CatSodaaa** [comment]
> 如果常用的方法不能解决这个问题，建议在`.src/client/ybplugins/clan_battle/components/realize.py`内34行上方插入下列代码以缩小排查范围：
> 
> ```
> print(FONTS)
> print(os.path.isfile(FONTS))
> ```
> 
> 插入并重启yobot后发送`状态`命令，在Exception抛出前应该会在控制台输出字体路径以及系统获取到的字体文件状态

已经解决了 运行主文件夹main.py文件即可 不运行打包好的yobot程序
