### ISSUE TITLE
公会战BOSS缺少

### ISSUE THREAD

**Issue by WenyiDong** [eggggi/yobot_remix#32]
作者您好，本次国服3月白羊座公会战，3王是巴吉里斯克，但是类表中缺少这个BOSS的选项，烦请指点如何添加该BOSS，谢谢

**Comment by eggggi** [comment]
可以去[干炸里脊资源站](https://redive.estertion.win/)找到该boss的头像，然后放到 ./src/client/public/libs/yocool@final/princessadventure/boss_icon/ 里，再在 default_BossIdAndName.json 和 BossIdAndName.json 加上对应的文件名和名字即可。

**Comment by eggggi** [comment]
还有，现在国服并没有更新新版会战，不建议用这个remix版

**Comment by mayochiki123** [comment]
提一个问题，default_BossIdAndName.json里面添加了对应的名字和文件名但是没有显示新的boss，请问BossIdAndName.json这个文件生成在了哪里，我没有找到

**Comment by eggggi** [comment]
生成在./src/client/yobot_data文件夹下

**Comment by xu040633** [comment]
现在更新了.jpg

**Comment by eggggi** [comment]
> 现在更新了.jpg

看到了，雷姆。写完差不多1年的remix版终于可以用来实战了

**Comment by xu040633** [comment]
> 

这个魔改版可以作为插件使用吗

**Comment by xu040633** [comment]
> > 现在更新了.jpg
> 
> 看到了，雷姆。写完差不多1年的remix版终于可以用来实战了

这个魔改版可以作为插件使用吗

**Comment by eggggi** [comment]
> > > 现在更新了.jpg
> > 
> > 
> > 看到了，雷姆。写完差不多1年的remix版终于可以用来实战了
> 
> 这个魔改版可以作为插件使用吗

可以的，而且我个人也推荐作为hoshino的插件使用

**Comment by WenyiDong** [comment]
诶嘿，下个月公会战马上就要上场了，所以提早拿来用了，谢谢dalao指点！

**Comment by WenyiDong** [comment]
> > > > 现在更新了.jpg
> > > 
> > > 
> > > 看到了，雷姆。写完差不多1年的remix版终于可以用来实战了
> > 
> > 
> > 这个魔改版可以作为插件使用吗
> 
> 可以的，而且我个人也推荐作为hoshino的插件使用

我是拆分开来使用，都接在一个gocq上面，最早的时候作者说将hoshino和yobot分开会好些，就一直保留这个状态了，无非也就多占用一个端口2333

**Comment by eggggi** [comment]
其实都可以啦，看个人习惯\_(:з)∠)_

**Comment by WenyiDong** [comment]
非常感谢dalao
