### ISSUE TITLE
预约功能bug，新的预约会把老的预约顶掉，只会显示一个预约

### ISSUE THREAD

**Issue by mayochiki123** [eggggi/yobot_remix#33]
如题，对于同一个boss的预约会出现这样的情况，只会显示一个预约，并且最后预约提醒的时候也只会AT最后预约的那位成员

**Comment by eggggi** [comment]
可以了，更新下看看

**Comment by mayochiki123** [comment]
感谢回复，打完会战我更新一下试试

**Comment by mayochiki123** [comment]
继续这个问题，更新后在QQ群里预约和显示都正常了，但是web端显示是这样的
![QQ图片20230328204802](https://user-images.githubusercontent.com/129147055/228241298-9f1a22a6-0bda-4aff-81da-4755b267d741.png)
一旦预约人数超过一个人，预约红点上的提示依然是1，并且显示会变成图上这样

**Comment by eggggi** [comment]
修了 \_(:з)∠)_
