### ISSUE TITLE
 Could not find module \opencc.dll' (or one of its dependencies). Try using the full path with constructor syntax.

### ISSUE THREAD

**Issue by ReijiAkaba** [eggggi/yobot_remix#36]
add_dll_directory()了也还是报错无法执行

**Comment by eggggi** [comment]
这是什么。。哪里报的错，截图看看

**Comment by eggggi** [comment]
好像是opencc的问题，用pip list看看opencc的版本

**Comment by ReijiAkaba** [comment]
![image](https://user-images.githubusercontent.com/18699960/230374253-13f86d39-725e-452c-ae94-d01bb0cce475.png)
1.1.1的opencc

**Comment by ReijiAkaba** [comment]
报错在File "C:\bot\yobot_remix\src\client\yobot.py", line 18, in <module>
    from opencc import OpenCC
py版本3.8

**Comment by eggggi** [comment]
版本没问题。。找不到的话，感觉是环境变量问题，检查一下环境变量，或者uninstall之后重装一下
