### ISSUE TITLE
运行时出现OS错误：/lib64/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by Jacky117** [eggggi/yobot_remix#37]
安装依赖后，发现有OS报错，记得之前用过一段时间这个魔改版本是可以运行的，可能是更新了吧
![错误](https://user-images.githubusercontent.com/107171157/230364003-1281ccfd-4368-457f-913f-fbeb05d4deca.jpg)

**Comment by eggggi** [comment]
好像是opencc的问题，用pip list看看opencc的版本

**Comment by Jacky117** [comment]
看了下版本是这样：
OpenCC                                      1.1.1
opencc-python-reimplemented 0.1.6

**Comment by eggggi** [comment]
chatgpt这样说：
这个报错通常是由于程序在运行时依赖的glibc库版本不匹配引起的。具体地说，程序需要的是glibc 2.29版本，而你的系统安装的glibc版本低于这个要求。

你可以尝试以下几种方法解决这个问题：

1.升级glibc库：升级系统，或者手动安装glibc 2.29版本或以上的库文件。

2.使用LD_PRELOAD环境变量：在运行程序之前，使用export命令设置LD_PRELOAD环境变量，将glibc 2.29版本或以上的库文件路径加入其中，强制程序先加载这个库文件。例如：export LD_PRELOAD=/path/to/libc.so.6:/path/to/libm.so.6。

希望以上方法可以帮到你。

**Comment by eggggi** [comment]
感觉是新版opencc库导致这种情况，隔壁issues有位兄弟也是这个情况，不过他的是windows系统，应该是同一个问题 https://github.com/eggggi/yobot_remix/issues/36

**Comment by ReijiAkaba** [comment]
是的，一个问题，重装opencc-python-reimplemented后解决了，感谢

**Comment by Jacky117** [comment]
谢谢老哥，我重装了一下，现在可以正常跑了
