### ISSUE TITLE
输入状态没有反馈

### ISSUE THREAD

**Issue by IzumiKUN0905** [eggggi/yobot_remix#39]
创建工会、加入成员、报刀都正常，但是群内输入状态没有任何反馈

**Comment by eggggi** [comment]
看下日志是不是报错了，或者qq风控了

**Comment by IzumiKUN0905** [comment]
调试了一下代码发现是图片的问题，已经解决。
还有几个问题：
1.出刀记录指令的返回信息会提示发送失败可能被风控，我注释了出0刀名单部分即可成功发送
2.申请出刀成功的返回消息也提示风控，注释了self.challenger_info_small(group, boss_num, info)那行就可以了
3.希望挂树能和申请出刀解绑，比如挂树5就可以直接挂5王这样~
4.希望能把查树和挂树留言加回来，状态里可以不显示挂树信息~

**Comment by eggggi** [comment]
风控的话大多是qq自身的问题，可能是群友的名字太怪触发了tx的风控机制
