### ISSUE TITLE
无法取消预约

### ISSUE THREAD

**Issue by tang-bai** [eggggi/yobot_remix#4]
预约之后好像无法取消预约，还有个问题好像是一刀收了3个BOSS有一刀会算了到第二刀

**Comment by eggggi** [comment]
可以取消预约的，格式是 取消预约[1-5]
一刀是怎么打死3个boss的 Σ(っ °Д °;)っ

**Comment by tang-bai** [comment]
![image](https://user-images.githubusercontent.com/71223830/170443265-5c66f8ed-9f96-430c-8540-8495b001fe5f.png)
我试了取消预约1取消不掉哎

**Comment by tang-bai** [comment]
一刀全部打一丝可以打3个 不过我感觉没影响

**Comment by eggggi** [comment]
啊，取消预约报错了，晚点我修一下 \_(:з)∠)_
还有，一刀3个boss是不存在的，这是游戏机制问题，补偿刀不能再吃补偿，满补收丝血boss就是血亏

**Comment by tang-bai** [comment]
行

**Comment by tang-bai** [comment]
还有个问题是第3刀是尾刀的时候会出现没有补偿的情况，实际上收了这个boss应该还有个补偿的，这个补偿丢失了

![image](https://user-images.githubusercontent.com/71223830/170449329-eefaf041-be99-4155-8119-8676aa8e2d6c.png)

**Comment by eggggi** [comment]
> 还有个问题是第3刀是尾刀的时候会出现没有补偿的情况，实际上收了这个boss应该还有个补偿的，这个补偿丢失了
> 
> ![image](https://user-images.githubusercontent.com/71223830/170449329-eefaf041-be99-4155-8119-8676aa8e2d6c.png)

现在这个界面有显示bug，实际上是存在的，可以在群里发 状态 查看剩余的补偿刀数量。这个界面等我晚点有空的时候重写一下，搞起来有点麻烦。。 >_<

**Comment by tang-bai** [comment]
我测试发现是出完第二刀之后第3刀直接变成了余刀，导致第3刀报不了补偿

**Comment by eggggi** [comment]
> 我测试发现是出完第二刀之后第3刀直接变成了余刀，导致第3刀报不了补偿

逻辑是这样的。因为新版会战是可以自己选择出完整刀还是补偿刀，所以在申请出刀的时候可以选择出的是完整刀或补偿刀。如果一直不声明自己是否是补偿刀，则优先选择完整刀，如果已出完所有完整刀，后续就会自动选择补偿刀。用完整刀收了多少个boss就会有多少个补偿刀，即使不声明自己出的是补偿刀，一天能出的总刀数也是固定的，声不声明自己是否是补偿刀对一般公会来说问题不大。如果在无补偿刀的情况下，是不能声明自己出的是补偿刀的。你可以完整说一下你的具体出刀流程，我可以给你分析

**Comment by tang-bai** [comment]
如果目前创建为国服的公会也是这样子的机制吗

**Comment by eggggi** [comment]
是的，这个魔改的yobot就是为了新版会战机制而改的，只是现在国服未实装，提前放出来给大家熟悉下（顺便帮我找bug \_(:з)∠)_ ）

**Comment by tang-bai** [comment]
![YP)CW@OQM9IIXUR)CE~3(90](https://user-images.githubusercontent.com/71223830/170739230-68260d2d-d048-417f-8ddb-199adfb784c6.png)
![T$X5 JS3~RWT @4~UE_$C5Q](https://user-images.githubusercontent.com/71223830/170739311-55ded02d-8baf-422e-a0f9-fd76c5b62ac0.png)
![Screenshot_2022-05-28-00-19-15-928_com tencent mo](https://user-images.githubusercontent.com/71223830/170739549-493e7d8b-27d6-4467-a216-170779fa0294.png)
有人反馈这样子的问题，是因为目前国服问题导致的吗

**Comment by eggggi** [comment]
建议不要看查刀面板里的数据，因为现在是有显示bug的。想知道自己有没有补偿刀，直接发 状态 就行了，这个能确保是准确的。这个问题我看起来很正常，因为你报的这个尾刀就是补偿刀的尾刀，所以显示的是 尾余刀。第三刀的尾余刀出完之后就是完整出完所有刀了，这个没有问题。
要不你把我拉进你们测试群吧，我好参考下。我加你qq了 ヾ(•ω•`)o
