### ISSUE TITLE
关于状态展示面板改进

### ISSUE THREAD

**Issue by OREOCODEDEV** [eggggi/yobot_remix#40]
计划改进一下状态的展示面板，以提高可读性。[目前在我的分支上搓的内容](https://github.com/eggggi/yobot_remix/compare/stable...OREOCODEDEV:yobot_remix:status_image_support)

准备把预约表和申请出刀留言都做成`QQ头像+群昵称+备注`的chips形状，但是这样的话可能要加QQ头像缓存，我看现在的代码里面应该是没有做这一块，考虑定时刷新和异步请求缓存要动的刀可能有点多

你觉得这个改动咋样，有没有必要加QQ头像这一块（

下面是现在的样子，五个放一起的话背景色会用一点变化区分开（准备）
![tmp57386_d8](https://user-images.githubusercontent.com/44545625/230529748-67442d4a-1405-4beb-a5ec-722db3205561.PNG)

**Comment by eggggi** [comment]
qq头像已经有了的，在查刀界面能看到各个成员的qq头像。
这个想法很好，但是我写前端界面的水平实在太差qaq，如果你有兴趣就交给你来写了\_(:з)∠)_

**Comment by OREOCODEDEV** [comment]
> qq头像已经有了的，在查刀界面能看到各个成员的qq头像。 这个想法很好，但是我写前端界面的水平实在太差qaq，如果你有兴趣就交给你来写了_(:з)∠)_

这个是用Pillow搓的图片，不是前端，准备是替换掉`状态`命令发送的图片。~~前端我也不会~~
前端的查刀页面我看了，是直接请求的qlogo.cn，也没有在yobot内部做缓存应该

**Comment by eggggi** [comment]
凹，是我理解错了，我想成网页的状态面板了0.0。
现在的状态图确实很简陋，之前是为了避免太长导致风控然后才转成图片的0.0。像这样优化一下也可以，头像缓存的话，可以考虑在初始化的时候和发送`加入公会`的时候去qlogo.cn请求一下保存在内存，加个字段就行。

**Comment by OREOCODEDEV** [comment]
应该是就差一个头像缓存了，但是感觉信息密集度好像没有想象中那么高
而且配色好像没有想象中好看，~~来点美工~~
![tmp6df1iuxd](https://user-images.githubusercontent.com/44545625/230547679-3843a1ee-cd6d-47ba-a830-7a4523aea44f.PNG)

**Comment by AlanX3** [comment]
目前的`状态`图片会显示不全
![M7P5LC7PBULKLPD6VIVPKU7](https://user-images.githubusercontent.com/86391482/230548227-2d8b93fe-b0f0-43f1-abc6-bb4b876a86ac.PNG)

**Comment by OREOCODEDEV** [comment]
TODO:
- [ ] 动态画布大小生成，解除用户列表行数限制
- [ ] 用户Chips支持换行显示
- [ ] 加入其它命令的数据内容

**Comment by OREOCODEDEV** [comment]
> 目前的`状态`图片会显示不全 ![M7P5LC7PBULKLPD6VIVPKU7](https://user-images.githubusercontent.com/86391482/230548227-2d8b93fe-b0f0-43f1-abc6-bb4b876a86ac.PNG)

要不我pr合并了之后你更新一下看看有什么问题没（

**Comment by OREOCODEDEV** [comment]
最新的PR已经支持动态生成画布大小，现在可以生成无限长度和无限chips行数的画布了
目前限制剩下一个用户最多只能显示一行内容（排版算法限制暂时不支持换行）
状态面板改进和优化基本完成了，这个issue先关了到时候有需要再开（

**当前样式预览：**
![1652331953c8cd30](https://user-images.githubusercontent.com/44545625/230735617-5a7056e0-c4a5-4f3a-b68e-d43452bfb277.jpg)
