### ISSUE TITLE
大佬，这个作为插件怎么用呀_(:з」∠)_

### ISSUE THREAD

**Issue by kendajiwaimai** [eggggi/yobot_remix#42]
不打包的话加到插件里没反应，打包的话最后PyInstaller报错Unable to find "D:\python\lib\site-packages\opencc\config" when adding binary and data files.然后我查看opencc文件夹，并没有config这个文件。opencc版本为1.1.1，python版本为3.8

**Comment by eggggi** [comment]
这个的话先pip uninstall opencc，然后再重新安装就可以了 https://github.com/eggggi/yobot_remix/issues/37

**Comment by kendajiwaimai** [comment]
感谢大佬，打包成功力！
