### ISSUE TITLE
大佬，打包完成以后报这个错是因为什么呀？我想直接以插件形式运行，但是加入MODULES_ON中以后不生效，该如何解决呢？

### ISSUE THREAD

**Issue by kendajiwaimai** [eggggi/yobot_remix#52]
![QQ截图20230410204037](https://user-images.githubusercontent.com/42399023/230903964-b7d94bc7-d263-406d-ae49-fd94e1665a63.png)

**Comment by eggggi** [comment]
更新最新版本了吗，这个问题修过了的 https://github.com/eggggi/yobot_remix/issues/48

**Comment by kendajiwaimai** [comment]
更新了呀，用的是最新版本的。而且不知道为什么不能以插件的形式运行（插件放在了modules文件夹里，bot.py里也加了）

**Comment by eggggi** [comment]
截图看下路径

**Comment by kendajiwaimai** [comment]
![22](https://user-images.githubusercontent.com/42399023/230917234-14ec5e68-ec35-44f3-8bdc-50e259118b9a.png)
![333](https://user-images.githubusercontent.com/42399023/230917251-baf668b8-d9e5-459a-be36-28fce750189c.png)

**Comment by eggggi** [comment]
再套一层试一下，像这样 HoshinoBot/hoshino/modules/yobot_remix/yobot_remix/

**Comment by kendajiwaimai** [comment]
我勒个去，原来是这样解决的吗，太离谱了。我要给你一个大大的赞。多套一层以后再pip install expiringdict解决了= =
