### ISSUE TITLE
关于代挂树留言和挂树私聊通知

### ISSUE THREAD

**Issue by MiroticLAM** [eggggi/yobot_remix#54]
大佬，人号分离会因为有私聊需求所以把原本注释的代码改了回来，然后发现自己报挂树也会私聊自己╭(°A°`)╮
然后是代发挂树可以，但不能留言，留言会识别不到后面的艾特，感觉有点麻烦。

**Comment by cca2878** [comment]
PR有关于代挂的改动，你可以看看是否符合你的需求。

**Comment by eggggi** [comment]
代刀私聊我其实是建议关掉的，因为这个封号的概率很大。
关于挂树问题合并了上面hxd的pr了，可以更新下看下。

**Comment by MiroticLAM** [comment]
更新完没问题了，感谢各位大佬！
