### ISSUE TITLE
关于依赖项OpenCC 1.1.1的问题

### ISSUE THREAD

**Issue by liyk123** [eggggi/yobot_remix#58]
这个目前只有x86/amd64的架构才能支持，如果跑在arm的设备上直接gg，高版本的也只有苹果的macos arm64支持，建议调整依赖以提高兼容性，毕竟这种级别的运算并不一定需要x86的设备。

**Comment by eggggi** [comment]
这个库是简繁体切换相关的，感觉如果没有很必要的话可以直接去掉了（原版yobot的历史包袱Σ(っ °Д °;)っ）

**Comment by liyk123** [comment]
> 这个库是简繁体切换相关的，感觉如果没有很必要的话可以直接去掉了（原版yobot的历史包袱Σ(っ °Д °;)っ）

OK，那我先搞掉😂

**Comment by cca2878** [comment]
同样建议去除此依赖。此依赖在Python3.8及以上版本似乎不能正常工作（未从“可信位置”加载DLL）

**Comment by eggggi** [comment]
> 同样建议去除此依赖。此依赖在Python3.8及以上版本似乎不能正常工作（未从“可信位置”加载DLL）

去掉了\_(:з)∠)_
