### ISSUE TITLE
关于个人出刀记录的问题

### ISSUE THREAD

**Issue by aJacke** [eggggi/yobot_remix#61]
关于网页出刀记录中，全会统计出刀记录是正常的，但个人记录却是不对的。

![0U%1AXCFB_0AO24)D7RIIXI](https://user-images.githubusercontent.com/69704128/232551564-d48a77f9-b721-42c3-9ef3-e2d46ee17f1f.png)

![MFJMUTVFX5WL0{U1~5V1%X7](https://user-images.githubusercontent.com/69704128/232551619-a81e1369-17e3-4c31-a143-a20c0279163a.png)

![{_}5IVJE1VJ 1QT9R`Y)CZV](https://user-images.githubusercontent.com/69704128/232551630-02444260-8538-4558-a40e-d9349daf0147.png)

**Comment by aJacke** [comment]
我的问题，没有添加群记录

**Comment by eggggi** [comment]
网页的个人出刀记录修好了\_(:з)∠)_
