### ISSUE TITLE
临时会话私聊无法登陆问题

### ISSUE THREAD

**Issue by likingsdee** [eggggi/yobot_remix#62]
私聊登陆的时候，只有添加好友的才能正常获取登陆网址，从群里发起的临时会话无法正常获取登陆网址，是go-cqhttp设置不对还是yobot的配置有问题呢
![image](https://user-images.githubusercontent.com/37286077/233324520-6d59d9e1-77ce-4a80-aebd-4bb85e426785.png)
![image](https://user-images.githubusercontent.com/37286077/233324142-97127c91-14d2-43c2-b931-05f58cb706cc.png)

**Comment by eggggi** [comment]
腾讯的问题，建议加好友再私聊，不然很容易封号

**Comment by eggggi** [comment]
gocq的配置可以解除这个限制，但不建议

**Comment by likingsdee** [comment]
好的，多谢大佬
