### ISSUE TITLE
碰到个奇怪的bug,尾刀后数据异常,不回复

### ISSUE THREAD

**Issue by Dfight** [eggggi/yobot_remix#67]
![image](https://user-images.githubusercontent.com/29205736/233814354-57534ad8-f4c5-40f9-a48f-ce67b24ada52.png)
这里尾刀4王后,状态应该是1234王是6周目0血,无法继续挑战,5王是5周目满血状态
![image](https://user-images.githubusercontent.com/29205736/233814404-5059d687-eb17-4038-9147-653cab8a61c4.png)
这里申请出刀5,到这里还正常
![image](https://user-images.githubusercontent.com/29205736/233814419-1bd50a50-6d23-446d-bc0a-f0534f1e5e3f.png)
但是之后尾刀没有回复,且依旧是申请状态,无法继续申请
![image](https://user-images.githubusercontent.com/29205736/233814513-a05b1b13-7485-40a0-b910-aaef80586140.png)
此时看状态,申请没有解除,所有boss血量没变但是加了一个周目

**Comment by eggggi** [comment]
更新最新版本，你这很旧的了

**Comment by Dfight** [comment]
> 更新最新版本，你这很旧的了

一个月前说会战改版的时候 换上的 我换个新版本试试  yobot_data文件里的数据依旧通用是吧

**Comment by eggggi** [comment]
对，数据都通用

**Comment by Dfight** [comment]
更新了新版本,运行一下看看吧
换新版本还遇到一个问题,源码运行是没问题的,但是用pyinstaller打包后运行的时候遇到了和[https://github.com/eggggi/yobot_remix/issues/52](url)一样的问题,不过我是直接打包运行,没用hoshibot,我自己改了image_engine.py里15,16两行代码路径的获取方式,跑起来了,不知道后续会不会有问题

**Comment by eggggi** [comment]
> 更新了新版本,运行一下看看吧 换新版本还遇到一个问题,源码运行是没问题的,但是用pyinstaller打包后运行的时候遇到了和[https://github.com/eggggi/yobot_remix/issues/52](url)一样的问题,不过我是直接打包运行,没用hoshibot,我自己改了image_engine.py里15,16两行代码路径的获取方式,跑起来了,不知道后续会不会有问题

https://github.com/eggggi/yobot_remix/commit/201cab0f6026cd3c13b427d847ea0a32d2fee8db 应该修复了，看下你是不是也这样改的

**Comment by eggggi** [comment]
这个pr或许修复了这个问题 https://github.com/eggggi/yobot_remix/pull/72
