### ISSUE TITLE
很莫名的一个bug

### ISSUE THREAD

**Issue by kennywang-ubi** [eggggi/yobot_remix#68]
正常报刀到第三周目开始后，不知道为什么尾掉第三周目的1王后，bot直接报的是杀了4周目的1王，但是一周目全报完之后，数据又对了。。。。
![XSHF47ET7P{%IT3U~T3_6O8](https://user-images.githubusercontent.com/78527364/233816483-05235f0f-984b-425d-b32e-e33feecc9e28.png)

**Comment by kennywang-ubi** [comment]
另外还有个小bug，我这边不知道为啥无法识别用户出的是第几刀，完整刀全部报的第一刀

**Comment by eggggi** [comment]
什么意思，没看懂，哪里有问题吗

**Comment by eggggi** [comment]
3到4周目是跨面，不能跨面挑战两个周目。这个是正常的

**Comment by kennywang-ubi** [comment]
> 

第三周目的时候群员尾刀一王，但结果是显示四周目的一王死了无法挑战，而不是类似：
3周目1王，剩余0血
该boss无法继续挑战

不知道我这个补充是否清楚。。。确实很别扭的bug

**Comment by kennywang-ubi** [comment]
哦我大概懂这个发生的逻辑了，4周目是B所以锁挑战，但是又解锁了4，所以变成了没有显示3的0血。

我的我的，被提前解锁绕晕了

**Comment by eggggi** [comment]
这个不是bug，尾刀后默认是显示下周目boss，只能说是显示问题，而且这也算不上是问题

**Comment by kennywang-ubi** [comment]
> 这个不是bug，尾刀后默认是显示下周目boss，只能说是显示问题，而且这也算不上是问题

嗯嗯，对的，另外请教下，现在还有个问题是在报完整刀的时候所有刀的记录都会显示第一刀，这个keneng可能是什么导致的？
![image](https://user-images.githubusercontent.com/78527364/233816892-9809171e-6ecb-4e19-8024-daf6c18374ce.png)

**Comment by eggggi** [comment]
这个是历史遗留问题了，没报补偿的话会导致这种情况，这个我后续优化下

**Comment by kennywang-ubi** [comment]
> 这个是历史遗留问题了，没报补偿的话会导致这种情况，这个我后续优化下

感谢，辛苦啦

**Comment by eggggi** [comment]
这个问题有热心网友提交pr了，可以更新到最新版本看下
