### ISSUE TITLE
能适配Hoshino v4工会战指令么

### ISSUE THREAD

**Issue by roMummy** [eggggi/yobot_remix#7]
可以适配V4指令么？
现在的指令用起来怪怪的

![WechatIMG291](https://user-images.githubusercontent.com/19543632/176068602-1e19fcec-d5f0-4d6e-9ddb-96519bc3bdbe.jpeg)

**Comment by eggggi** [comment]
我没用过hoshino的会战模块0.0（v1234都没有）
我魔改的yobot命令是根据原版yobot延申的，hoshino v4的命令看起来逻辑和原版yobot完全不同，要适配的话需要非常大的工作量，我是懒狗\_(:з)∠)_
