### ISSUE TITLE
状态查询不能正常显示

### ISSUE THREAD

**Issue by WenyiDong** [eggggi/yobot_remix#70]
蛮怪的，前一天特地更新了一下，觉得太久没更新了，现在是查刀功能正常，有反馈。但是状态没有反应。
我以为是风控了图片发不出来，我登录了go-cqhttp的后台查看，也没有BOT发言的样子，如果被风控了应该会看见图片发送失败的日志
烦请dalao帮忙看看是啥情况，是指令变了吗
![image](https://user-images.githubusercontent.com/62381678/233832311-ac7e3634-6e5a-4f36-af55-8d0c8b486656.png)
![image](https://user-images.githubusercontent.com/62381678/233832375-66bb0592-6a0f-491b-985c-218f65b7fc74.png)

**Comment by eggggi** [comment]
那大概率就是报错了，看下yobot的日志

**Comment by WenyiDong** [comment]
已补充日志，dalao回复的好快！
![image](https://user-images.githubusercontent.com/62381678/233832886-40297dd8-38da-4d88-8995-0bb06e68289e.png)

**Comment by eggggi** [comment]
看下你的PIL库版本，估计是版本太低了

**Comment by WenyiDong** [comment]
![image](https://user-images.githubusercontent.com/62381678/233833137-c7bbf1c1-45b9-4eb8-b344-5769de919a48.png)
7.2.0，以前部署了就没更新过了，需要多少版本的才可以呀，因为服务器上还有别的东西在跑，所以尽可能变动小hhh

**Comment by eggggi** [comment]
我的是Pillow==9.4.0，最好更新下吧

**Comment by WenyiDong** [comment]
> 

已更新至9.4.0，哇原来改动了这么多，现在成功了，非常感谢

![image](https://user-images.githubusercontent.com/62381678/233833776-feb9d0c7-b80b-488e-bdb5-e568d0d535fe.png)
