### ISSUE TITLE
[BUG]:自动判断剩余刀错误`连续报2个尾刀时候容易把第二刀默认判断于剩余刀`

### ISSUE THREAD

**Issue by Sam5440** [eggggi/yobot_remix#73]
貌似自动判断出问题了，改成强制必须带b报剩余刀?
![image](https://user-images.githubusercontent.com/47051833/233848232-9d002d45-dc38-45df-ac2c-c0a066fbf6ed.png)
`Path : src\client\ybplugins\clan_battle\components\realize.py`
![image](https://user-images.githubusercontent.com/47051833/233848495-01024c1d-c791-401e-91bf-4dc2ce9e13b2.png)

**Comment by eggggi** [comment]
自动选择补偿的意思是，出刀的总次数基本不会变，当没有完整刀时会自动选择补偿刀来打。即使完整刀当作补偿打或者补偿当作完整打也无所谓，伤害正确就行了的。机器人实际并不知道你在游戏里打的是补偿还是完整刀（臣妾做不到啊qaq）。中后排公会建议不用太在意这个指定补偿的问题。

**Comment by Sam5440** [comment]
> 自动选择补偿的意思是，出刀的总次数基本不会变，当没有完整刀时会自动选择补偿刀来打。即使完整刀当作补偿打或者补偿当作完整打也无所谓，伤害正确就行了的。机器人实际并不知道你在游戏里打的是补偿还是完整刀（臣妾做不到啊qaq）。中后排公会建议不用太在意这个指定补偿的问题。

就是连续两刀尾刀的话，第二道正常的尾刀被当做补偿刀来算。 就会少一刀补偿刀。

**Comment by eggggi** [comment]
不会哇，怎么触发的，是不是已经出过两刀完整刀了

**Comment by Sam5440** [comment]
> 不会哇，怎么触发的，是不是已经出过两刀完整刀了

我也挺纳闷的，莫名其妙碰到两次，我明天再看看吧，刚刚去复现也没有复现出来。

**Comment by cca2878** [comment]
大概是因为现在可以自由选择出尾刀还是出补偿刀，但是yobot仍然和之前一样默认出完尾刀后下一刀必是这个尾刀产生的补偿刀，应该也是原版yobot的遗留问题，会战打完再修。

**Comment by wuhaoyu1993** [comment]
完全不指定的话，按照，1收尾，2丢补偿，3打完整刀，4再收尾的顺序打完，最后一个补偿打了就会报不上去了

**Comment by cca2878** [comment]
> 完全不指定的话，按照，1收尾，2丢补偿，3打完整刀，4再收尾的顺序打完，最后一个补偿打了就会报不上去了

因为bot会把你的某个尾刀错误地认为是尾余刀（即补偿刀收尾），而尾余刀不会产生补偿刀，因此总体上就少了一个补偿，最后一个补偿自然报不上去。

今晚看看能不能修好。

**Comment by cca2878** [comment]
目前该问题已修复(*^▽^*)
