### ISSUE TITLE
有一个小小的问题，希望大佬帮忙看看

### ISSUE THREAD

**Issue by zhtyirg3** [eggggi/yobot_remix#74]
大佬好，我是新改的魔改版，之前一直用的原版。这个版本非常合理，很好用，但是有一个小瑕疵。就是4王获取失败了，明明这期打的乌龟，却获取成了鹿。这是哪里设置有问题呢？
![1](https://user-images.githubusercontent.com/55908974/233848945-12ba2f75-3c04-426f-bcdb-561feaa8cf98.png)

**Comment by eggggi** [comment]
这个是一年前上一次金牛座的boss数据，因为我是在那个时候做的。改的话要进到设置里面改
![98$CI`N1LF `FHJWQ`CHV9](https://user-images.githubusercontent.com/49231933/233849126-d756b874-225d-4862-8a3b-eac57866f21a.png)
![M9LT3UJZP{RY M{ZO{9IHC8](https://user-images.githubusercontent.com/49231933/233849162-d3bc7cf1-cfab-45fc-889d-b7771caa5a87.png)

**Comment by zhtyirg3** [comment]
> 这个是一年前上一次金牛座的boss数据，因为我是在那个时候做的。改的话要进到设置里面改 ![98$CIN1LF FHJWQ`CHV9](https://user-images.githubusercontent.com/49231933/233849126-d756b874-225d-4862-8a3b-eac57866f21a.png) ![M9LT3UJZP{RY M{ZO{9IHC8](https://user-images.githubusercontent.com/49231933/233849162-d3bc7cf1-cfab-45fc-889d-b7771caa5a87.png)

我这边打开这个设置项，展开失败了，都是空白。还有现在bot不能私发重启yobot功能了吗？
<img width="2552" alt="image" src="https://user-images.githubusercontent.com/55908974/233849302-40a0f798-b265-4f09-886a-ee70aec9615e.png">

**Comment by eggggi** [comment]
ctrl+f5刷新缓存
重启功能之前删掉了，如果有需要的话我晚点加回来

**Comment by zhtyirg3** [comment]
> ctrl+f5刷新缓存 重启功能之前删掉了，如果有需要的话我晚点加回来

<img width="732" alt="image" src="https://user-images.githubusercontent.com/55908974/233849901-a1389ffe-6a32-452b-a1d4-3b16edfe70b7.png">
我删除了缓存，还是无效，不知道什么情况，这一页都是空白的

**Comment by eggggi** [comment]
按f12看看，是不是报错了

**Comment by zhtyirg3** [comment]
> 按f12看看，是不是报错了

<img width="529" alt="image" src="https://user-images.githubusercontent.com/55908974/233850032-7104036d-4e08-4d2d-baa6-41dcd63bcaae.png">
这个应该是有错误

**Comment by eggggi** [comment]
你旧版yobot的配置删掉让它重新生成，删掉yobot_data文件夹

**Comment by zhtyirg3** [comment]
> 

我之前就是真个文件夹删除，然后用新的版本去覆盖的

**Comment by eggggi** [comment]
实在不清楚你这个是什么情况，直接复制整个项目下来单独跑一下main.py看看，不要覆盖任何东西

**Comment by zhtyirg3** [comment]
> 实在不清楚你这个是什么情况，直接复制整个项目下来单独跑一下main.py看看，不要覆盖任何东西

找到原因了，就是yobot_data的问题，重新测试删除了，然后重新生成，但是公会要重新创建，所有的配置都要重新弄。现在只能等会战之后再测试了。谢谢！

**Comment by eggggi** [comment]
如果你是只有自己公会在用的话，建议等他们出完刀之后就搞一下，不然后面高阶段之后血量会不对。先记录一下打到哪里了，然后搞好之后修改状态
