### ISSUE TITLE
无法通过yobot的网页端修改boss周目血量

### ISSUE THREAD

**Issue by along411** [eggggi/yobot_remix#75]
点击展开boss设置血量变成空白了

**Comment by eggggi** [comment]
删除原版yobot配置，yobot_data文件夹，ctrl+f5清除缓存刷新页面

**Comment by along411** [comment]
我更换了admin下的资源之后可用，还有当机器人进度进行到5个王都在35周目时还是C面血量没有变成D面血量

**Comment by eggggi** [comment]
带点截图或日志信息

**Comment by along411** [comment]
![QQ图片20230424000413](https://user-images.githubusercontent.com/73514958/233850893-0185f175-2184-4d28-b5b3-8bebed3395df.png)
![QQ截图20230424000425](https://user-images.githubusercontent.com/73514958/233850899-355e01ff-a228-40ad-a5b1-12a8095230a8.png)
这样子

**Comment by eggggi** [comment]
设置项呢，这里有报错是吗
![image](https://user-images.githubusercontent.com/49231933/233850975-888c0456-343d-4e64-93ab-43347298981d.png)

**Comment by along411** [comment]
OK，已经通过boss设置调整周目了，原来的没有修改3阶段之后所以没有切换
