### ISSUE TITLE
尾刀之后不提示报刀成功但是查询状态会显示已经报上了

### ISSUE THREAD

**Issue by along411** [eggggi/yobot_remix#79]
![_06LO~C0 R77GD3IC9{2R29](https://user-images.githubusercontent.com/73514958/233967391-04d2531d-674c-4287-8581-a586235ee39b.png)

**Comment by along411** [comment]
正常报刀会有提示，就只有尾刀没有提示

**Comment by eggggi** [comment]
群里发送`手动添加群记录`试试
