### ISSUE TITLE
boss切换阶段数后血量不会自动补满

### ISSUE THREAD

**Issue by CYDXDianXian** [eggggi/yobot_remix#8]
例如四阶段向五阶段切换时，当成员全部挑战完毕后，boss变为五阶段了，最大血量随之改变，但当前血量没有被补满，数值为四阶段的最大血量。同时尝试了三阶段切四阶段，同样遇到了这样的问题，其他时候没有问题，只有在阶段切换时才会出现，麻烦作者大大看看如何解决，感谢！
![image](https://user-images.githubusercontent.com/71607036/176232964-c57da30c-c324-4677-bcc8-b84b515d55c5.png)

**Comment by eggggi** [comment]
bug get! 这就去改

**Comment by eggggi** [comment]
改好了\_(:з)∠)_

**Comment by CYDXDianXian** [comment]
感谢作者大大！
