### ISSUE TITLE
跨阶段跨两周目，boss状态可能判断有误

### ISSUE THREAD

**Issue by madoka315** [eggggi/yobot_remix#81]
公会刚碰到的，不确定是哪里导致的问题。
具体的实际情况是：43-44圈的1-4王已经打完，剩下43-44圈的牛。然后击败43圈和44圈的牛之后，1~4王变为46周目了。

自己测试了一下，过程如下：
· 当前周目43：
1-4王 下一周目0血（显示为44周目0血）
5王 当前周目满血（显示为43周目满血）
· 击败5王后，当前周目44：
1-4王 下一周目0血（显示为45周目0血）
5王 当前周目满血（显示为44周目满血）
· 击败5王后，当前周目45：
1-4王 下一周目满血 （显示为46周目满血）
5王 当前周目满血（显示为45周目满血）
直接复现的操作如下：
当前周目为44，手动修改1-4王为下一周目0血，5王为当前周目满血，击败5王后1-4王变成46周目满血

求指点
![)RXD(O4%DW0PG@R0(8~UM%P](https://user-images.githubusercontent.com/72589546/234034129-7d3a6e97-eb4c-4327-95cf-5f2483274637.png)

**Comment by cca2878** [comment]
直接复现方法属于酒吧点炒饭行为（）
目前的会战机制是不允许跨阶段的，也就是说你的牛爷爷在44周目的时候其他四个王不可能能打45周目，即便当前为44周目。

然后按照你的测试流程测试了一下，确实会出现当前44周目显示45周目0血这样的“错误”，但是在五王进入45周目之后其他王并没有再向前推一周目，而是变为45周目满血。

并且我并不认为这是一个“错误”，这可以代表该boss当前阶段已讨伐完毕，等待进入下一阶段。（上例中也许保持44周目0血会更加符合直觉）

建议更新到最新代码验证。

**Comment by madoka315** [comment]
> 直接复现方法属于酒吧点炒饭行为（） 目前的会战机制是不允许跨阶段的，也就是说你的牛爷爷在44周目的时候其他四个王不可能能打45周目，即便当前为44周目。
> 
> 然后按照你的测试流程测试了一下，确实会出现当前44周目显示45周目0血这样的“错误”，但是在五王进入45周目之后其他王并没有再向前推一周目，而是变为45周目满血。
> 
> 并且我并不认为这是一个“错误”，这可以代表该boss当前阶段已讨伐完毕，等待进入下一阶段。（上例中也许保持44周目0血会更加符合直觉）
> 
> 建议更新到最新代码验证。
 
![image](https://user-images.githubusercontent.com/72589546/234065722-71143156-24c2-487a-9454-459867c518f6.png)
刚才pull到最新版本，又测试了几遍，发现问题仍然存在，找到触发的方法如下：
先调整至当前周目为43周目，1-4王状态为“下一周目 0血”，5王状态为“当前周目 满血”。此时就是当时场景的实际情况。
1：通过在群聊中正常报刀来击败43-44周目的5王，则进入E阶段时，1-4王更新为45周目满血；
2：在群聊中正常报刀击败43周目的5王。此时在网页面板中点击“修改状态”，不做任何血量调整，仅切换到5王点击“修改”按钮，随后击败44周目的5王，则进入E阶段时，1-4王更新为46周目满血。
联想到当时可能是有管理员调整过血量，所以测试发现还真是跟这个有影响。希望能看看问题所在，第二种测试方法毕竟也是实际会出现的场景。

**Comment by cca2878** [comment]
> > 直接复现方法属于酒吧点炒饭行为（） 目前的会战机制是不允许跨阶段的，也就是说你的牛爷爷在44周目的时候其他四个王不可能能打45周目，即便当前为44周目。
> > 然后按照你的测试流程测试了一下，确实会出现当前44周目显示45周目0血这样的“错误”，但是在五王进入45周目之后其他王并没有再向前推一周目，而是变为45周目满血。
> > 并且我并不认为这是一个“错误”，这可以代表该boss当前阶段已讨伐完毕，等待进入下一阶段。（上例中也许保持44周目0血会更加符合直觉）
> > 建议更新到最新代码验证。
> 
> ![image](https://user-images.githubusercontent.com/72589546/234065722-71143156-24c2-487a-9454-459867c518f6.png) 刚才pull到最新版本，又测试了几遍，发现问题仍然存在，找到触发的方法如下： 先调整至当前周目为43周目，1-4王状态为“下一周目 0血”，5王状态为“当前周目 满血”。此时就是当时场景的实际情况。 1：通过在群聊中正常报刀来击败43-44周目的5王，则进入E阶段时，1-4王更新为45周目满血； 2：在群聊中正常报刀击败43周目的5王。此时在网页面板中点击“修改状态”，不做任何血量调整，仅切换到5王点击“修改”按钮，随后击败44周目的5王，则进入E阶段时，1-4王更新为46周目满血。 联想到当时可能是有管理员调整过血量，所以测试发现还真是跟这个有影响。希望能看看问题所在，第二种测试方法毕竟也是实际会出现的场景。

按第二种方法复现成功…可能是限制跨阶段刀的的机制导致的…已加入TODO…
