### ISSUE TITLE
想问一下怎么获取BOSS血量信息

### ISSUE THREAD

**Issue by Azusa-Yuan** [eggggi/yobot_remix#86]
每期的BOSS血量都不一样，我没在插件里找到配置BOSS血量信息或者类似的东西，希望能解答下困惑，谢谢

**Comment by eggggi** [comment]
机器人主人权限才能看到和更改。主页设置项往下拉，能看到boss数据
![SE61STX 6{~7YN~H5%3Y7$2](https://user-images.githubusercontent.com/49231933/237048849-4d8ed74c-eed1-41ba-9896-83c0a8a019ca.png)
![E5B7WADP26~I~LM80(12B6Y](https://user-images.githubusercontent.com/49231933/237048871-1677681c-9953-46b5-a47d-b20509371a46.png)

**Comment by Azusa-Yuan** [comment]
> 机器人主人权限才能看到和更改。主页设置项往下拉，能看到boss数据 ![SE61STX 6{7YNH5%3Y7$2](https://user-images.githubusercontent.com/49231933/237048849-4d8ed74c-eed1-41ba-9896-83c0a8a019ca.png) ![E5B7WADP26ILM80(12B6Y](https://user-images.githubusercontent.com/49231933/237048871-1677681c-9953-46b5-a47d-b20509371a46.png)

明白了 非常感谢，我关闭issue了
