### ISSUE TITLE
网页面板“我的”页出刀记录显示错误

### ISSUE THREAD

**Issue by cca2878** [eggggi/yobot_remix#89]
在“查刀”页正确显示：
![QQ截图20230528023936](https://github.com/eggggi/yobot_remix/assets/51525400/7ddbd0d3-4709-43ca-9ecc-35d2ee3b733a)
但在“我的”页则显示不正确，将一个完整刀（2337w那个）误当做补偿刀，将一个补偿刀（439w，已按补偿刀格式报刀）误当做完整刀：
![QQ截图20230528023912](https://github.com/eggggi/yobot_remix/assets/51525400/7b0271b3-d42c-447a-8898-45fcc81fb617)

由于我对web开发一窍不通（），只能先提issue期望大佬解决了。

**Comment by eggggi** [comment]
好了\_(:з)∠)_
