### ISSUE TITLE
私聊登录发了消息但没收到

### ISSUE THREAD

**Issue by XiaoFuOS** [eggggi/yobot_remix#91]
![image](https://github.com/eggggi/yobot_remix/assets/103229747/7abeac2b-d445-46a9-8911-9968e10fc9c8)
如图，已经发了，但qq上没收到，总不能私聊风控吧，群里功能一切正常

**Comment by eggggi** [comment]
gocq的问题，等gocq更新，或者根据这个issues修改 https://github.com/Mrs4s/go-cqhttp/issues/2164

**Comment by XiaoFuOS** [comment]
> gocq的问题，等gocq更新，或者根据这个issues修改 [Mrs4s/go-cqhttp#2164](https://github.com/Mrs4s/go-cqhttp/issues/2164)

那还是等gocq更新吧，换手表协议就用不了戳一戳力QAQ
