### ISSUE TITLE
Bot私聊被风控，怎么本地修改登录

### ISSUE THREAD

**Issue by RyanJiang184** [eggggi/yobot_remix#94]
**版本**：ReMix-[v4.0.2]

go-cqhttp

Python：3.8.10

**操作系统** Windows Server 2012 R2 Datacenter

**问题描述** Bot私聊被风控，想知道如何修改本地文件添加登录信息或者重置登录数据。找了半天没找到数据在哪里。

**Comment by eggggi** [comment]
用的gocqhttp吗？这个是tx最近在搞事情，只能等gocq更新，可以尝试删掉gocq生成的device和token文件重新生成一下，运气好的话或许就可以了。https://github.com/eggggi/yobot_remix/issues/91
