### ISSUE TITLE
网页端发现报刀问题

### ISSUE THREAD

**Issue by cadaeibf1** [eggggi/yobot_remix#96]
1. 不能在还有整刀的情况下使用网页端单独报补偿刀，选项可以选，但是没用，还是会报成整刀

**Comment by eggggi** [comment]
改了，更新下 \_(:з)∠)_

**Comment by cadaeibf1** [comment]
更新了以后，网页报刀出现了这个东西……不论是击杀与否都会出现

![5B59E97A38E33416EB871E73BD753A00](https://github.com/eggggi/yobot_remix/assets/65361365/a02f08bc-8d09-442d-8f18-17d96ddd91d4)

**Comment by eggggi** [comment]
ctrl+f5清空缓存刷新页面

**Comment by cadaeibf1** [comment]
清除cookie可以了，Thanks♪(･ω･)ﾉ
