### ISSUE TITLE
更新到最新版本三王还是没有巴吉里斯克

### ISSUE THREAD

**Issue by SakuraMay** [eggggi/yobot_remix#98]
更新完毕后检查了json和webp，均有。然后重启BOT后更改3王下拉列表还是没有

**Comment by eggggi** [comment]
yobot_data里的BossIdAndName.json也得改，复制一份default_BossIdAndName.json进去就行

**Comment by SakuraMay** [comment]
> yobot_data里的BossIdAndName.json也得改，复制一份default_BossIdAndName.json进去就行

谢谢，我去试试

**Comment by Special-Week** [comment]
新布置的应该是没问题
覆盖更新之前布置的话, 没法覆盖已经生成的yobot_data, 需要手动添加
