### ISSUE TITLE
关于丢失的3号boss巴吉里斯克

### ISSUE THREAD

**Issue by sagiriyo** [eggggi/yobot_remix#99]
当前版本改完之后的版本网页没生效
经过排查再这个文件夹的这个文件也改了就可以了
希望作者大大改善一下谢谢喵
![image](https://github.com/eggggi/yobot_remix/assets/76777320/5b9f02d5-c78e-40ff-bd55-12e41134dc3e)
![image](https://github.com/eggggi/yobot_remix/assets/76777320/5f884dd5-c9ae-4017-8a4c-14e55ea1b600)

**Comment by sagiriyo** [comment]
是未生效的改这里  写错了

**Comment by Special-Week** [comment]
这个是你布置完后生成的文件夹, 仓库里就没有yobot_data这个文件夹
如果是新布置的话是没问题的
https://github.com/eggggi/yobot_remix/issues/98

**Comment by cca2878** [comment]
只需要把这个文件删掉就行了

**Comment by eggggi** [comment]
新增了自动获取boss数据，不用再手动改了
![image](https://github.com/eggggi/yobot_remix/assets/49231933/53ce9875-f446-45be-aedb-8aaadc5684a1)
![image](https://github.com/eggggi/yobot_remix/assets/49231933/63ec345c-a858-4fcd-9695-d879b5f94676)
（依赖[公主连结box](https://pcr.satroki.tech/)的api，这个网站暂时没更新日服7月的boss数据所以获取不了）

**Comment by 964788339** [comment]
@eggggi 我刚更新了，提示没有hoshino，我一直都是独立运行的
![image](https://github.com/eggggi/yobot_remix/assets/61876981/1d8092ba-e97d-4195-8a78-1efa8b41fc18)

**Comment by eggggi** [comment]
> @eggggi 我刚更新了，提示没有hoshino，我一直都是独立运行的 ![image](https://user-images.githubusercontent.com/61876981/255834891-1d8092ba-e97d-4195-8a78-1efa8b41fc18.png)

对吼，忘了这茬。这就改成aiohttp

**Comment by 964788339** [comment]
问下这个怎么部署在hoshino里面，在bot.py里面添加名字没有加载
![6X`CKV9G%J~O%W0{C( AG4R](https://github.com/eggggi/yobot_remix/assets/61876981/082f3bba-d83a-42dd-af94-150ee6e1afc3)

**Comment by 964788339** [comment]
> > @eggggi 我刚更新了，提示没有hoshino，我一直都是独立运行的 ![image](https://user-images.githubusercontent.com/61876981/255834891-1d8092ba-e97d-4195-8a78-1efa8b41fc18.png)
> 
> 对吼，忘了这茬。这就改成aiohttp

问下这个怎么部署在hoshino里面，我在bot.py添加名字没有加载，搞不懂
![6X`CKV9G%J~O%W0{C( AG4R](https://github.com/eggggi/yobot_remix/assets/61876981/ba5ed646-769b-4533-8750-8e3b9691ce51)

**Comment by eggggi** [comment]
modules目录再套一层yobot_remix就行了，像这样HoshinoBot/hoshino/modules/yobot_remix/yobot_remix/

**Comment by eggggi** [comment]
> > @eggggi 我刚更新了，提示没有hoshino，我一直都是独立运行的 ![image](https://user-images.githubusercontent.com/61876981/255834891-1d8092ba-e97d-4195-8a78-1efa8b41fc18.png)
> 
> 对吼，忘了这茬。这就改成aiohttp

改好了 \_(:з)∠)_

**Comment by 964788339** [comment]
> > > @eggggi 我刚更新了，提示没有hoshino，我一直都是独立运行的 ![image](https://user-images.githubusercontent.com/61876981/255834891-1d8092ba-e97d-4195-8a78-1efa8b41fc18.png)
> > 
> > 
> > 对吼，忘了这茬。这就改成aiohttp
> 
> 改好了 _(:з)∠)_

感谢，可以了，我刚试下了获取不到数据，挂vpn也不行
![@~{F73@M(WAQQW`NI 1}SVJ](https://github.com/eggggi/yobot_remix/assets/61876981/22b0b895-f48b-4d78-9dd8-d6a99b6110a6)

**Comment by eggggi** [comment]
梯子关掉就行了

**Comment by 964788339** [comment]
试过了，开关都不行

> 梯子关掉就行了

试过了开关都不行

**Comment by eggggi** [comment]
这得检查你的网络设置了，是不是限制了python进程的网络或者单独给python进程挂了代理

**Comment by 964788339** [comment]
> 这得检查你的网络设置了，是不是限制了python进程的网络或者单独给python进程挂了代理

感谢，我烤到本地上可以成功获取了，估计是服务器的网络问题
